name: caldav_client
description: A CalDAV client for dart. It allows to make CalDAV
  requests to a server easily and quickly.
version: 1.1.0
repository: https://github.com/meltzow/caldav_client
issue_tracker: https://github.com/meltzow/caldav_client/issues

environment:
  sdk: '>=3.0.0'

dependencies:
  xml: ^6.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  mock_web_server: ^5.0.0-nullsafety.1
